#
# Dotrix Build
#
# @author Natesh Narain <nnaraindev@gmail.com>
#

os: Visual Studio 2015
platform:
  - amd64

clone_folder: c:\projects\dotrix

before_build:
  - set QT_ROOT=C:\Qt\5.7\msvc2015_64
  - set PATH=%PATH%;%QT_ROOT%\bin;"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64"
  - qmake --version
  - qtenv2.bat
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%

  - git clone --depth=1 --branch=0.17.0 https://github.com/nnarain/gameboycore.git c:\tmp\gameboycore
  - cd c:\tmp\gameboycore
  - mkdir build && cd build
  - cmake .. -G "NMake Makefiles" -DBUILD_TESTS="OFF" -DBUILD_EXAMPLE="OFF" -DCMAKE_INSTALL_PREFIX=c:\libs\gameboycore
  - nmake
  - nmake install
  - set PATH=%PATH%;c:\libs\gameboycore

build_script:
  - cd c:\projects\dotrix
  - mkdir build && cd build
  - cmake .. -G "NMake Makefiles"
  - nmake

after_build:
  - cd c:\projects\dotrix\build
  - nmake package

artifacts:
- path: .\build\Dotrix-*-win*.exe
  name: installer

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'v$(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: +F7/lKFe9fc9q4w0lCpc9tR1H4JucHiE7WuevfJCaWOeU/5ul8QojqNACB6ODFgT
  artifact: installer
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
  force_update: true
